[package]
name = "neurocr"
version = "0.1.0"
authors = ["legeyda"]

[dependencies]
mnist = "0.4.0"
rulinalg = "0.4.2"
num = "0.1.36"
log = "0.4.1"
env_logger = "0.5.3"
rand = "0.4"
simple_logger = "0.5"